# Generated by Django 5.0.1 on 2024-02-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(choices=[('Independent', 'Independent'), ('Orange', 'Orange'), ('Banana', 'Banana')], default='Independent', max_length=100)),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
