# Generated by Django 5.0.1 on 2024-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='party',
            field=models.CharField(choices=[('Orange', 'Orange'), ('Independent', 'Independent'), ('Banana', 'Banana')], default='Independent', max_length=100),
        ),
    ]
