# Generated by Django 4.2.2 on 2024-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Banana', 'Banana'), ('Orange', 'Orange'), ('Independent', 'Independent')], default='Independent', max_length=100),
        ),
    ]
