# Generated by Django 5.0.1 on 2024-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Banana', 'Banana'), ('Independent', 'Independent'), ('Orange', 'Orange')], default='Independent', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school',
            field=models.CharField(blank=True, choices=[('SCI', 'SCI'), ('SPAS', 'SPAS'), ('SAFS', 'SAFS'), ('SON', 'SON'), ('SBE', 'SBE'), ('SEA', 'SEA'), ('SED', 'SED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seat',
            field=models.CharField(choices=[('WOMENS_REP', 'WomenRep'), ('MEN_REP', 'MenRep'), ('SCHOOL_REP', 'SchoolRep'), ('PRESIDENT', 'President')], max_length=200),
        ),
    ]
