# Generated by Django 4.2.5 on 2024-02-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Banana', 'Banana'), ('Independent', 'Independent'), ('Orange', 'Orange')], default='Independent', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school',
            field=models.CharField(blank=True, choices=[('SEA', 'SEA'), ('SPAS', 'SPAS'), ('SCI', 'SCI'), ('SBE', 'SBE'), ('SON', 'SON'), ('SAFS', 'SAFS'), ('SED', 'SED')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seat',
            field=models.CharField(choices=[('SED_REP', 'SedRep'), ('SBE_REP', 'SbeRep'), ('SCI_REP', 'SciRep')], max_length=200),
        ),
    ]
