# Generated by Django 5.0.1 on 2024-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0002_alter_president_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(choices=[('Banana', 'Banana'), ('Independent', 'Independent'), ('Orange', 'Orange')], default='Independent', max_length=100)),
                ('seat', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('votes', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='President',
        ),
    ]
