# Generated by Django 4.2.5 on 2024-02-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0002_alter_candidate_party_alter_candidate_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Orange', 'Orange'), ('Banana', 'Banana'), ('Independent', 'Independent')], default='Independent', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school',
            field=models.CharField(blank=True, choices=[('SON', 'SON'), ('SPAS', 'SPAS'), ('SEA', 'SEA'), ('SAFS', 'SAFS'), ('SBE', 'SBE'), ('SED', 'SED'), ('SCI', 'SCI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seat',
            field=models.CharField(choices=[('SCHOOL_REP', 'SchoolRep'), ('WOMENS_REP', 'WomenRep'), ('PRESIDENT', 'President')], max_length=200),
        ),
    ]
