# Generated by Django 5.0.1 on 2024-02-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('president', '0003_candidate_delete_president'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('Independent', 'Independent'), ('Banana', 'Banana'), ('Orange', 'Orange')], default='Independent', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
